### PR TITLE
updated deepgram_token function

### PR DESCRIPTION
**Pull request by SandraRodgers**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202714578363470

### CODE REVIEW

**Review by lukeocodes — CHANGES_REQUESTED** [review]
I get an error running this, did it work for you?

**Comment by SandraRodgers** [comment]
> I get an error running this, did it work for you?

I have now updated it with the serverless functions deploy URL, but it gives a CORS error. I already have `headers: { "access-control-allow-origin": "*" },` in the function. Is there something I need to do in Netlify to fix the cors error?

**Comment by lukeocodes** [comment]
image
this is the error i get. i'm guessing it just needs the url for the deployed function?

**Comment by lukeocodes** [comment]
Now working in deploy and local

**Review by lukeocodes — APPROVED** [review]

**Pull request merged**
