### PR TITLE
Add codeplayground component to the component library

### PR DESCRIPTION
**Pull request by SandraRodgers**

### CODE REVIEW

**Review by MichaelJolley — COMMENTED** [review]
Do we need to add a "code components" card to the components page?

**Comment by lukeocodes** [comment]
> Do we need to add a "code components" card to the components page?

@MichaelJolley I considered this. I thought "CMS components" should be anything that is going to be usable inside the CMS

**Review by lukeocodes — CHANGES_REQUESTED** [review]
Can you add an example of this to the CMS components page?

Inside the example snippet's property, just leave the src as "..." rather than a real URL.

**Review by MichaelJolley — APPROVED** [review]

**Comment by MichaelJolley** [comment]
@SandraRodgers can you cleanup the merge conflicts?

**Review by MichaelJolley — APPROVED** [review]

**Pull request merged**
